### ISSUE TITLE
"Dead" Questgivers throw an animation error (FreezeAnimation)

### ISSUE THREAD

**Issue by RealoFoxtrot** [Total-RP/Storyline#85] opened 2023-08-12 02:29 UTC
Have seen this a few times now, most recently it's happened with the character Meeki, who ends an opening quest in Voldun. There may be a quicker NPC, however this one is fairly easy to access if not done voldun yet (the questline is always active as it's a sidequest)

https://www.wowhead.com/npc=136287/meeki

Description:

Upon interactive with a questgiver who is considered "Dead", an error pops up that says the game can't freeze the animation and the quest text doesn't fully load. It only loads a short part of the first paragraph.

Reproduction steps:

Talk to an NPC who the game considers Dead.
Example, Meeki, end questgiver for Lost In Zem'lam

Error Code Below:

`Message: Interface/AddOns/Storyline/PlayerModelMixin.lua:111: Usage: self:FreezeAnimation(anim, variation, frame)
Time: Sat Aug 12 03:26:15 2023
Count: 4
Stack: Interface/AddOns/Storyline/PlayerModelMixin.lua:111: Usage: self:FreezeAnimation(anim, variation, frame)
[string "=[C]"]: in function `FreezeAnimation'
[string "@Interface/AddOns/Storyline/PlayerModelMixin.lua"]:111: in function `DisplayDead'
[string "@Interface/AddOns/Storyline/events.lua"]:495: in function <Interface/AddOns/Storyline/events.lua:457>
[string "@Interface/AddOns/Storyline/events.lua"]:529: in function <Interface/AddOns/Storyline/events.lua:513>
[string "@Interface/AddOns/Storyline/logic.lua"]:310: in function <Interface/AddOns/Storyline/logic.lua:211>
[string "@Interface/AddOns/Storyline/events.lua"]:765: in function <Interface/AddOns/Storyline/events.lua:763>

Locals: (*temporary) = Storyline_NPCFrameModelsYou {
 OnModelLoaded = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:58
 SetModelFacing = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:269
 RequiresManualAnimationTiming = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:103
 ResetIdleAnimationID = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:79
 SetModelUnit = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:91
 SetModelFeet = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:275
 SetModelHeight = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:263
 SetModelOffset = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:281
 modelLoadedPromise = <table> {
 }
 offset = 0.215000
 debug = Storyline_NPCFrameDebugSequenceYou {
 }
 OnAnimFinished = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:228
 AnimateScalingValuesIn = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:287
 PlayAnimation = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:142
 animationStartedTime = 0
 displayedModel = 1890761
 currentAnimation = 0
 isModelLoaded = false
 isPlayingAnimationSequence = false
 isPlayingIntersticeAnimation = true
 sequence = <table> {
 }
 facing = 0.750000
 SetCustomIdleAnimationID = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:73
 boundSetModelHeight = <function> defined @Interface/AddOns/Storyline/lib/Ellyb/Tools/Functions.lua:21
 scale = 2.320000
 SetScalingValuesIn = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:294
 modelFeetTransitionator = <table> {
 }
 animationTries = 0
 animTab = <table> {
 }
 npc_id = "136287"
 isModelDisplayedOnLeft = false
 doNotAnimateScaling = false
 modelOffsetTransitionator = <table> {
 }
 0 = <userdata>
 DisplayDead = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:107
 GetValidSpeakingAnimation = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:117
 modelHeightTransitionator = <table> {
 }
 PlayIdleAnimation = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:149
 GetModelFileIDAsString = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:302
 OnLoad = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:42
 PlayAnimSequence = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:156
 boundSetModelFeet = <function> defined @Interface/AddOns/Storyline/lib/Ellyb/Tools/Functions.lua:21
 ReplayAnimation = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:224
 feet = 0.400000
 SetAnimationWithFailSafe = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:208
 boundSetModelOffset = <function> defined @Interface/AddOns/Storyline/lib/Ellyb/Tools/Functions.lua:21
 ModelLoaded = <function> defined @Interface/AddOns/Storyline/logic.lua:130
 PlayNextAnimation = <function> defined @Interface/AddOns/Storyline/PlayerModelMixin.lua:179
 idleAnimationID = 0
 scroll = Button {
 }
 ResetModel = <func`

**Comment by Solanya** [comment] 2023-08-12 02:30
Duplicate of #84

**Closed by Solanya** 2023-08-12 02:30 UTC
